"""empty message

Revision ID: 2fabed7a2797
Revises: 
Create Date: 2022-07-06 00:38:09.662446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fabed7a2797'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('greenhouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('plant', sa.String(length=200), nullable=True),
    sa.Column('postcode', sa.String(length=200), nullable=True),
    sa.Column('plantingDate', sa.Integer(), nullable=True),
    sa.Column('forSale', sa.Boolean(), nullable=True),
    sa.Column('bookedForSale', sa.Boolean(), nullable=True),
    sa.Column('energyPlan', sa.Integer(), nullable=True),
    sa.Column('harvestDate', sa.String(length=1000), nullable=True),
    sa.Column('counterForAVG', sa.Integer(), nullable=True),
    sa.Column('AVGofAirTemperature', sa.Integer(), nullable=True),
    sa.Column('GivenDaysWeather', sa.Integer(), nullable=True),
    sa.Column('currentParameters', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('greenhouses')
    op.drop_table('user')
    # ### end Alembic commands ###
