"""empty message

Revision ID: 76580e5eb1d9
Revises: 2fabed7a2797
Create Date: 2022-08-10 22:51:07.508304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76580e5eb1d9'
down_revision = '2fabed7a2797'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('testtime', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'testtime')
    # ### end Alembic commands ###
