"""empty message

Revision ID: a85e68376bbe
Revises: 4a7e6a3c0dc1
Create Date: 2022-08-14 22:33:29.593707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a85e68376bbe'
down_revision = '4a7e6a3c0dc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('greenhouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('bookedForSale', sa.Boolean(), nullable=True),
    sa.Column('recordDateTime', sa.String(length=200), nullable=True),
    sa.Column('LightRelay', sa.Boolean(), nullable=True),
    sa.Column('LightCurrent', sa.Boolean(), nullable=True),
    sa.Column('FanRelay', sa.Boolean(), nullable=True),
    sa.Column('FanCurrent', sa.Boolean(), nullable=True),
    sa.Column('OutsideTemp', sa.Integer(), nullable=True),
    sa.Column('InsideTemp', sa.Integer(), nullable=True),
    sa.Column('Lightsensor', sa.Boolean(), nullable=True),
    sa.Column('AirheaterRelay', sa.Boolean(), nullable=True),
    sa.Column('AirHeaterCurrent', sa.Boolean(), nullable=True),
    sa.Column('WaterPumpCurrent', sa.Boolean(), nullable=True),
    sa.Column('WaterHeaterRelay', sa.Boolean(), nullable=True),
    sa.Column('WaterHeaterCurrent', sa.Boolean(), nullable=True),
    sa.Column('WaterTemp', sa.Integer(), nullable=True),
    sa.Column('AirPumpCurrent', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('greenhouses')
    # ### end Alembic commands ###
