"""empty message

Revision ID: c698638b432c
Revises: 62e08afd69e0
Create Date: 2022-08-11 00:21:21.255368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c698638b432c'
down_revision = '62e08afd69e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('testtime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'testtime')
    # ### end Alembic commands ###
